export const siteConfig = {
  name: 'Star Stucco of Austin',
  shortName: 'Star Stucco',
  tagline: 'Integrity \u00B7 Commitment \u00B7 Quality',
  description: 'Star Stucco of Austin is a stucco and plaster contractor serving Central Texas. Residential stucco, commercial stucco, EIFS, interior plaster, and stone veneer. Over 9,000 projects completed.',
  phone: '(512) 706-9699',
  phoneHref: 'tel:+15127069699',
  email: 'info@starstuccoaustin.com',
  address: {
    street: '5316 W US Hwy 290 Service Rd',
    city: 'Austin',
    state: 'TX',
    zip: '78735',
    county: 'Travis County',
  },
  coordinates: {
    lat: 30.2672,
    lng: -97.7431,
  },
  url: 'https://stuccoaustin.com',
  serviceAreas: [
    'Austin',
    'Round Rock',
    'Cedar Park',
    'Georgetown',
    'Pflugerville',
    'Westlake',
    'Lakeway',
    'Bee Cave',
    'Dripping Springs',
    'Kyle',
  ],
  serviceCounties: [
    'Travis County',
    'Williamson County',
    'Bell County',
    'Burnet County',
    'Llano County',
    'Hays County',
    'Comal County',
    'Bastrop County',
    'Blanco County',
    'Gillespie County',
    'Caldwell County',
    'Lee County',
    'Milam County',
    'Brazos County',
    'McLennan County',
    'Guadalupe County',
  ],
  hours: {
    weekday: '24/7',
    weekend: '24/7',
  },
  neighborhoods: [
    'South Congress',
    'East Austin',
    'The Domain',
    'Westlake Hills',
    'Barton Hills',
    'Mueller',
    'Hyde Park',
    'Travis Heights',
    'Tarrytown',
    'Circle C Ranch',
  ],
  socialMedia: {
    facebook: 'https://facebook.com/starstuccoaustin',
    instagram: 'https://instagram.com/starstuccoaustin',
    google: 'https://g.page/starstuccoaustin',
  },
} as const
